name: Build Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Auth service
        run: docker build -t auth-service:latest ./auth

      - name: Build Product service
        run: docker build -t product-service:latest ./product

      - name: Build Order service
        run: docker build -t order-service:latest ./order

      - name: Build API Gateway
        run: docker build -t api-gateway:latest ./api-gateway

      - name: List Docker images
        run: docker images
