name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    # Dịch vụ chạy cùng để test (Mongo + RabbitMQ)
    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672

    steps:
      # B1: Lấy code
      - name: Checkout code
        uses: actions/checkout@v3

      # B2: Tạo file .env cho từng service
      - name: Create .env files
        run: |
          # --- auth service ---
          echo "MONGODB_AUTH_URI=mongodb://mongo:27017/ep_auth_db" >> auth/.env
          echo "JWT_SECRET=11042004" >> auth/.env
          echo "RABBITMQ_URI=amqp://rabbitmq" >> auth/.env

          # --- product service ---
          echo "MONGODB_AUTH_URI=mongodb://mongo:27017/ep_auth_db" >> product/.env
          echo "MONGODB_PRODUCT_URI=mongodb://mongo:27017/ep_product_db" >> product/.env
          echo "JWT_SECRET=11042004" >> product/.env
          echo "RABBITMQ_URI=amqp://rabbitmq" >> product/.env
          echo "LOGIN_TEST_USER=test@example.com" >> product/.env
          echo "LOGIN_TEST_PASSWORD=123456" >> product/.env

          # --- order service ---
          echo "MONGODB_AUTH_URI=mongodb://mongo:27017/ep_auth_db" >> order/.env
          echo "MONGODB_PRODUCT_URI=mongodb://mongo:27017/ep_product_db" >> order/.env
          echo "MONGODB_ORDER_URI=mongodb://mongo:27017/ep_order_db" >> order/.env
          echo "JWT_SECRET=11042004" >> order/.env
          echo "RABBITMQ_URI=amqp://rabbitmq" >> order/.env

      # B3: Cài dependencies
      - name: Install dependencies
        run: |
          cd auth && npm ci
          cd ../product && npm ci
          cd ../order && npm ci
          cd ..

      # B4: Chạy test cho Auth
      - name: Run tests for auth
        run: |
          cd auth
          npm test

      # B5: Chạy test cho Product
      - name: Run tests for product
        run: |
          cd auth && npm start &
          cd ../product
          npm test

      # B6: Chạy test cho Order
      - name: Run tests for order
        run: |
          cd auth && npm start &
          cd ../product && npm start &
          cd ../order
          npm test
